public class ArthimaticCalculations {
    public void addition(integer x, integer y){
        integer z = x + y;
        system.debug('Sum: ' + z);
    }
    public void substraction(integer x, integer y){
        integer subs = x - y;
        system.debug('Result of substraction: ' + subs);
        
    }
    public void multiplication(integer x, integer y, integer m){
        integer multp = x * y * m;
        system.debug('Result of multiplication: ' + multp); 
    }
}
