public class CheckDataTypes {
    public void MethodBoolean(){
        boolean checkBoolean = true;
        system.debug(checkBoolean);
    }

    public void MethodInteger(){
        integer varFirst = 1;
        integer varSecond = 2;

        system.debug(varFirst);
        system.debug(varSecond);
        
    }

    public void StringMethod(){
        string varName = 'Name';
        string var2Name = 'your name';

        system.debug(varName);
        system.debug(var2Name);
    }
}
