public class Address {
    public void HomeAddress() {
        string myName = 'Zeynep';
        system.debug('My name is ' + myName);
        integer totalNumOfFamilyMem = 5;
        system.debug('My total number of family member is ' + totalNumOfFamilyMem);
        string houseName = 'Yellow Home';
        system.debug('My house name is ' + houseName);
        string houseNumber = '234';
        system.debug('My house number is ' + houseNumber);
        string streetName = 'Amity';
        system.debug('My street name is ' + streetName);
        string cityName = 'KFC';
        system.debug('My city name is ' + cityName);
        string stateName = 'Lagos';
        system.debug('My state name is '+  stateName);
        string isoCode = '3166-2:AU';
        system.debug('My ISO Code is ' +  isoCode);
        string countryName = 'Nijerya';
        system.debug('My country name is ' + countryName);
        string coutryIsoCode = '3166-3:AU';
        system.debug('My country ISO Code is ' + coutryIsoCode);
        string zipCode = '2345';
        system.debug('My zip code is ' + zipCode);
        boolean isYourCurrentHome = true;
        system.debug('Is this your current home or not?: ' + isYourCurrentHome);

        }
}

/*1. Your Name
2. Total number of members in your family
3. House Name
4. House Number
5. Street Name
6. City Name
7. State Name
8. State ISO Code
9. Country Name
10. Country ISO Code
11. Zip Code
12. Is this your current home or not*/