public class TurkishRevisio1 {
    public integer metot1(string text){
        integer uzunluk = text.length();
        return uzunluk;
    }
    public integer method2(integer x){
        string sInteger = string.valueOf(x);
        integer lengthOfNum = sInteger.length();

        return lengthOfNum;
    }
    public integer sum(integer a, integer b){
        return a + b;
    }
    public integer multp(integer a, integer b){
        return a * b;
    }
    
}
