Students st1 = new Students();
st1.firstName= 'Yusuf';
st1.lastName = 'Yildiz';
st1.classYear = 10;
st1.major = 'Math';
system.debug(st1.generateReport());
system.debug('info about st1 is ' + st1);

Students st2 = new Students();
st2.firstName = 'Zeynep';
st2.lastName = 'Fidan';
st2.classYear = 5;
st2.major = 'Science';
system.debug(st2.generateReport());
system.debug('info about st2 is ' + st2);



